  pod 'SSZipArchive', '~> 2.2.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo/scripts/autolinking'

source 'https://github.com/CocoaPods/Specs.git'


def get_custom_flags()
  flags = {
    :fabric_enabled => false,
    :hermes_enabled => false,
  }

  #if ENV['HERMES_ENABLED'] == 'true'
  #  flags[:hermes_enabled] = true
  #end

  return flags
end

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false


target 'ulil-albab' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  #use_frameworks! :linkage => :static

  project 'ulil-albab/ulil-albab.xcodeproj'
  # Pods for ulil-albab
  config = use_native_modules! 
 
  flags = get_custom_flags()

  use_expo_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'boost', :podspec => '../node_modules/react-native/third-party-podspecs/boost.podspec'
  # pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
  # pod 'ExpoModulesCore', :modular_headers => true

  target 'ulil-albabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ulil-albabUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  react_native_post_install(installer)
  #__apply_Xcode_15_1_M1_post_install_workaround(installer)

  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"

      # additional config for xcode 14
      #config.build_settings["DEVELOPMENT_TEAM"] = "JGN252G28Z"
    end
  end

end
